# Generated by Django 3.1.7 on 2021-03-16 09:06

import django.core.validators
from django.db import migrations, models
import esite.colorfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('color', esite.colorfield.fields.ColorField(help_text='Select color that fitd your mood.', max_length=18, null=True)),
                ('brightness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('color_temperature', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6500), django.core.validators.MinValueValidator(2700)])),
                ('color_from_temperature', models.BooleanField(blank=True, null=True)),
                ('effect', models.CharField(blank=True, choices=[('rainbow', 'Rainbow'), ('blink', 'Blink')], max_length=32, null=True)),
            ],
        ),
    ]
