# Generated by Django 3.1.7 on 2021-03-16 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='brightness',
            field=models.FloatField(blank=True, default=0.5, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='light',
            name='color_from_temperature',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='light',
            name='color_temperature',
            field=models.IntegerField(blank=True, default=2700, null=True, validators=[django.core.validators.MaxValueValidator(6500), django.core.validators.MinValueValidator(2700)]),
        ),
        migrations.AlterField(
            model_name='light',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
