# Generated by Django 3.1.7 on 2021-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0002_auto_20210316_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='topic',
            field=models.CharField(default='server/mqtt-test/COMMAND', max_length=32),
        ),
    ]
