# Generated by Django 3.1.7 on 2021-03-16 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0003_light_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='brightness',
            field=models.FloatField(blank=True, default=100, null=True, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)]),
        ),
    ]
