# Generated by Django 3.1.7 on 2021-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0004_auto_20210316_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='topic',
            field=models.CharField(default='test_bulb/light/test_bulb/command', max_length=64),
        ),
    ]
