# Generated by Django 3.1.7 on 2021-03-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0006_auto_20210316_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='color',
            new_name='hcolor',
        ),
    ]
