# Generated by Django 3.1.8 on 2021-04-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='config',
            field=models.TextField(blank=True, default='[\n    {"symbol": ""},\n    {"name": " Name: "},\n    {"price_btc": " Price in BTC: "},\n    {"price": " Price: "},\n    {"percent_change_24h": " - 24 Hour Percent Change: "},\n    {"market_cap": " Market Cap: "},\n    {"volume_24h": " 24 Hour Volume: "},\n    {"url_shares": " URL Shares: "},\n    {"reddit_posts": " Reddit Posts: "},\n    {"tweets": " Tweets: "},\n    {"news": " News: "},\n    ]'),
        ),
    ]
